<?php

return [
    'UTC-12' => 'Pacific/Kwajalein',
    'UTC-11' => 'Pacific/Midway',
    'UTC-10' => 'Pacific/Honolulu',
    'UTC-9' => 'America/Anchorage',
    'UTC-8' => 'America/Los_Angeles',
    'UTC-7' => 'America/Denver',
    'UTC-6' => 'America/Chicago',
    'UTC-5' => 'America/New_York',
    'UTC-4' => 'America/Caracas',
    'UTC-3' => 'America/Argentina/Buenos_Aires',
    'UTC-2' => 'Atlantic/South_Georgia',
    'UTC-1' => 'Atlantic/Azores',
    'UTC' => 'Europe/London',
    'UTC+1' => 'Europe/Paris',
    'UTC+2' => 'Europe/Budapest',
    'UTC+3' => 'Europe/Moscow',
    'UTC+4' => 'Asia/Dubai',
    'UTC+5' => 'Asia/Karachi',
    'UTC+6' => 'Asia/Almaty',
    'UTC+7' => 'Asia/Bangkok',
    'UTC+8' => 'Asia/Singapore',
    'UTC+9' => 'Asia/Tokyo',
    'UTC+10' => 'Australia/Sydney',
    'UTC+11' => 'Pacific/Guadalcanal',
    'UTC+12' => 'Pacific/Auckland',
];